### ISSUE TITLE
点击全员静音的时候，确实实现静音了，但是视频也相对应的关闭了,应该是所有人员静音

### ISSUE THREAD

**Issue by mylixin** [wildfirechat/vue-chat#100]
点击全员静音的时候，确实实现静音了，但是视频也相对应的关闭了,应该是所有人员静音

_Originally posted by @mylixin in https://github.com/wildfirechat/vue-chat/issues/99#issuecomment-1846721569_

**Comment by imndx** [comment]
已解决，请更新测试
