### ISSUE TITLE
发送文件时，wfc.sendMessage()这个方法的progressCB回调只在文件发送完的时候返回了一次数据

### ISSUE THREAD

**Issue by zhaoxinmeiX** [wildfirechat/vue-chat#105]
oss 配置的是本地硬盘
<img width="633" alt="image" src="https://github.com/wildfirechat/vue-chat/assets/81342340/7b012a4d-5a04-4fb2-9647-cc5b9de35d68">

**Comment by heavyrain2012** [comment]
如果是PC客户端，上传时，如果数据比较小，则只会回调一次，是C++协议栈的处理方式的问题。如果文件比较大，则会回调多次

**Comment by imndx** [comment]
已解决
