### ISSUE TITLE
如何自定义消息发送状态

### ISSUE THREAD

**Issue by cfmj** [wildfirechat/vue-chat#107]
场景:
前端发送文件消息
1. 发送大文件到自建oss服务器(此时发送文件消息,并且消息状态是发送中)
2. 上传进度赋值到消息对象中
3. 文件发送完毕,获取到资源链接
4. 消息发送完成

该如何实现上述场景(消息部分)

**Comment by imndx** [comment]
下面是大概流程：
1. 插入一条消息，`message.status`置为发送中
2. 上传完成之后，更新消息
3. `sendSaveMessage`

**Comment by cfmj** [comment]
> 下面是大概流程：
> 
> 1. 插入一条消息，`message.status`置为发送中
> 2. 上传完成之后，更新消息
> 3. `sendSaveMessage`

1/2 是调用`wfc.sendMessage` 在插入本地的回调里更改 `message.status` 吗?
3 `sendSaveMessage` 有导出这个api吗 没有在wfc.js找到这个方法

**Comment by imndx** [comment]
1. `insertMessage`
2. `updateMessageContent`
3. `sendSavedMessage`
