### ISSUE TITLE
调用getGroupPortrait生成群头像异常

### ISSUE THREAD

**Issue by cfmj** [wildfirechat/vue-chat#108]
有概率获取不到群成员 导致生成失败

**Comment by imndx** [comment]
最新代码，已经不用这个接口了，采用 app-server 生成默认头像

**Comment by cfmj** [comment]
为什么会获取不到群成员信息呢?  我们业务上需要在前端生成群头像

**Comment by imndx** [comment]
> 为什么会获取不到群成员信息呢? 我们业务上需要在前端生成群头像

你参考下这个 https://github.com/wildfirechat/vue-pc-chat/issues/184

**Comment by cfmj** [comment]
已解决
