### ISSUE TITLE
集成到自己的vue3 vite 项目中 报错  The requested module '/src/wfc/ptt/internal/ptt.min.js' does not provide an export named

### ISSUE THREAD

**Issue by zslgod** [wildfirechat/vue-chat#109]
vite 版本为5.4.0  按照文档把 wfc 目录还有 config.js ， platform.js 复制到自己项目之后  main.js 中调用 wfc.init(); 浏览器控制台报错 pttClient.js:3  Uncaught SyntaxError: The requested module '/src/wfc/ptt/internal/ptt.min.js' does not provide an export named 'default' (at pttClient.js:3:9)

**Comment by imndx** [comment]
你参考下 `babel.config.js`的配置

或者你直接改下 `wfc.js`，不引入`pttClient`

**Comment by zslgod** [comment]
注释 pttClient 相关之后能正常使用， babel.config.js的配置看了，但是不知道在vite下如何处理，能否给个示例

**Comment by imndx** [comment]
> 注释 pttClient 相关之后能正常使用， babel.config.js的配置看了，但是不知道在vite下如何处理，能否给个示例

你好，这个问题的根本原因是 vite 只支持 ESM，下面是 ESM 版本的 ptt.min.js 文件，你试下。
[ptt.min.js](https://static.wildfirechat.cn/ptt.min.js)

**Comment by zslgod** [comment]
> > 注释 pttClient 相关之后能正常使用， babel.config.js的配置看了，但是不知道在vite下如何处理，能否给个示例
> 
> 你好，这个问题的根本原因是 vite 只支持 ESM，下面是 ESM 版本的 ptt.min.js 文件，你试下。 [ptt.min.js](https://static.wildfirechat.cn/ptt.min.js)

感谢回复，可以了
