### ISSUE TITLE
web的IM API 在哪里查看

### ISSUE THREAD

**Issue by lmq352489099** [wildfirechat/vue-chat#110]
比如发送消息,创建群聊 等等web IM的API详细的 清单接口功能

**Comment by imndx** [comment]
请查看 ```wfc.js```文件

**Comment by lmq352489099** [comment]
> 请查看 `wfc.js`文件

有提供相应的文档吗

**Comment by lmq352489099** [comment]
野火有提供会话列表的筛选吗
![image](https://github.com/user-attachments/assets/b76eeef4-84b1-4b1e-811a-65375efe1b5b)

**Comment by imndx** [comment]
这个，你可以在 UI 层自己分类一下

或者，可以通过会话类型，或者会话线路区分的你们的不同会话，然后通过下面这个 api
```    /**
     * 获取会话列表
     * @param {[number]} types 想获取的会话类型，可选值参考{@link ConversationType}
     * @param {[0]} lines 想获取哪些会话线路的会话，默认传[0]即可
     * @returns {[ConversationInfo]}
     */
    getConversationList(types, lines) {
        return impl.getConversationList(types, lines);
    }

```

**Comment by lmq352489099** [comment]
好的 谢谢



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年10月14日(星期一) 下午3:38
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [wildfirechat/vue-chat] web的IM API 在哪里查看 (Issue #110)














 
这个，你可以在 UI 层自己分类一下
 
或者，可以通过会话类型，或者会话线路区分的你们的不同会话，然后通过下面这个 api
      * 获取会话列表      * @param {[number]} types ***@***.*** ConversationType}      * @param {[0]} lines 想获取哪些会话线路的会话，默认传[0]即可      * @returns {[ConversationInfo]}      */     getConversationList(types, lines) {         return impl.getConversationList(types, lines);     }
