### ISSUE TITLE
想实现群二维码

### ISSUE THREAD

**Issue by EF03** [wildfirechat/vue-chat#12]
请问一下，现在是否已有现成的api可以怎么使用
或是在app server实现 大概流程会怎么实现

**Comment by imndx** [comment]
1. 移动端群二维码的前缀是这么定义的：
```
String QR_CODE_PREFIX_GROUP = "wildfirechat://group/";
```
2. 在前缀的基础上拼接上群 id，形成完整的字符串:
```
wildfirechat://group/a_group_id
```
3. 调用```jrQRCode.getQrBase64('wildfirechat://group/a_group_id')```即可生成一个 base64 格式的二维码
