### ISSUE TITLE
請問如何自定义讯息?

### ISSUE THREAD

**Issue by EF03** [wildfirechat/vue-chat#15]
目前在app server中群发自定义事件 MessagePayload type = 1001
store.js 中的 EventType.ReceiveMessage 有印出自定义讯息
![image](https://user-images.githubusercontent.com/47837419/155044940-913896d0-899b-4b03-ab25-7110005fce78.png)
现在不确定怎么在聊天列表取出这则讯息 劳烦提点 感谢

**Comment by imndx** [comment]
1. 参考```TextMessageContent```完成消息的定义，注意```encode```和```decode```等方法要各端统一
2. 在 ```messageConfig.js```完成自定义消息的注册

**Comment by EF03** [comment]
感谢

**Comment by cfmj** [comment]
请问没有注册该自定义消息,是不是收不到这条消息?
