### ISSUE TITLE
会话数据一一直在减少

### ISSUE THREAD

**Issue by KNJON** [wildfirechat/vue-chat#16]
![image](https://user-images.githubusercontent.com/31526763/155120496-d5a28543-725d-45cc-b5dd-ef6e2b773020.png)

当前数据是调用stroe.js中的_loadCurrentConversationMessages方法，再调用wfc.getMessages（）获取的数据.
目前是17条，每隔一段数据刷新页面，重新调用_loadCurrentConversationMessages获取当前会话记录的时候就会发现数据变少了，最后数据为0.

![image](https://user-images.githubusercontent.com/31526763/155121225-9501342b-d537-4d7d-80ff-947c49811ef5.png)
10分钟后，数据就没有了

**Comment by imndx** [comment]
1. 请确认两张截图中的```currentConversation```是不是同一个```Conversation```
2. 刷新之后，默认加载最近 100 条消息，如果其他会话有信息消息了，就会导致【当前会话】的消息变少。

**Comment by KNJON** [comment]
已解决，后台数据问题
