### ISSUE TITLE
引入TextMessageContent报Super

### ISSUE THREAD

**Issue by wangjiake** [wildfirechat/vue-chat#21]
Super expression must either be null or a function
集成到自己项目单独调发送消息报这个
新建了一个vue项目调用单独引入这个也报相同的错误

inherits.js?262e:4 Uncaught TypeError: Super expression must either be null or a function
    at _inherits (inherits.js?262e:4:1)
    at eval (ptextMessageContent.js?96c7:9:1)
    at eval (ptextMessageContent.js?96c7:9:1)
    at Module../wfc/messages/ptextMessageContent.js (app.js:1868:1)
    at __webpack_require__ (app.js:849:30)
    at fn (app.js:151:20)
    at eval (messageConfig.js:8:87)
    at Module../wfc/client/messageConfig.js (app.js:1352:1)
    at __webpack_require__ (app.js:849:30)
    at fn (app.js:151:20)

**Comment by imndx** [comment]
你好，我们 demo 也引入了 ```PTextMessageContent``` 和 ```TextMessageContent```，但是没有报错；上面的错误日志也没看出问题。

是否可以给我们提供一个能复现这问题的，最简 demo？

**Comment by wangjiake** [comment]
vue create demo2    
cd demo2 
然后把 wfc目录 ，config.js  ，platform.js ， windowEmitter.js 拷贝到根目录
然后 src下面的 app.js 引入TextMessageContent 就会有了

<template>
  <div id="app">
    <img alt="Vue logo" src="./assets/logo.png">
    <HelloWorld msg="Welcome to Your Vue.js App"/>
  </div>
</template>

<script>
import HelloWorld from './components/HelloWorld.vue'
import TextMessageContent from "../wfc/messages/textMessageContent";
export default {
  name: 'App',
  components: {
    HelloWorld
  },
  created(){
    let d = new TextMessageContent();
    console.log(d);
  }
}
</script>

<style>
#app {
  font-family: Avenir, Helvetica, Arial, sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  text-align: center;
  color: #2c3e50;
  margin-top: 60px;
}
</style>

**Comment by imndx** [comment]
不知道原因是什么，但这样就能工作：

```
import HelloWorld from "./components/HelloWorld.vue";
import PTextMessageContent from '../wfc/messages/ptextMessageContent'
import TextMessageContent from "../wfc/messages/textMessageContent";
export default {
  name: "App",
  components: {
    HelloWorld,
  },
  created() {
    let d = new TextMessageContent();
    console.log(d);
    let e = new PTextMessageContent();
    console.log(e);
  },
};
```

**Comment by imndx** [comment]
找到原因了：
简单说是循环依赖导致的问题

```imprort TextMessageContent```时，会触发```import PTextMessageContent```，```PTextMessageContent```的定义会使用到```TextMessageContent```，但此时```import TextMessageContent```尚未完成，```TextMessageContent```还是```undefined```，故导致上面的错误。

解决办法：
确保使用```web sdk```时，```import wfc from "../wfc/client/wfc";```在导入其他任何```web sdk```相关内容之前执行。

[更多参考](https://lifesaver.codes/answer/super-expression-must-either-be-null-or-a-function-not-undefined)
