### ISSUE TITLE
多人会议音视频声音异常

### ISSUE THREAD

**Issue by Dooley0509** [wildfirechat/vue-chat#22]
苹果手机浏览器多人会议时，经常出现听对方声音忽大忽小，小的时候就像听筒模式一样。

**Comment by imndx** [comment]
是同一个人的声音会忽大忽小，还是固定某个人的声音是大的，另外一个人的声音是小的？

**Comment by Dooley0509** [comment]
> 是同一个人的声音会忽大忽小，还是固定某个人的声音是大的，另外一个人的声音是小的？

这个没注意，下次测试在碰到的时候会留意一下。
