### ISSUE TITLE
自定义消息转码错误

### ISSUE THREAD

**Issue by EF03** [wildfirechat/vue-chat#24]
需求: 
	想要自定义群组通知消息在decode时发生"'atob' failed: The string to be decoded is not correctly encoded"
	消息是由 app server 使用 MessageAdmin.sendMessage 想在聊天室做出群组的通知消息

结果:
![image](https://user-images.githubusercontent.com/47837419/159386883-3e4dba53-b734-4748-8dab-e715ac190228.png)

继承GroupNotificationContent:
![image](https://user-images.githubusercontent.com/47837419/159386903-08368a49-acc7-4235-a614-69d11a05b957.png)

decode错误位置:
![image](https://user-images.githubusercontent.com/47837419/159386943-8a1e12e4-eaf7-4095-bc3b-12d890392cea.png)

错误訊息:
![image](https://user-images.githubusercontent.com/47837419/159386970-97ae3996-732e-4a18-a77c-096da89b6752.png)

**Comment by imndx** [comment]
请贴一下完整的 ```TestGroupNotification```

**Comment by EF03** [comment]
复制CreateGroupNotification的，发现问题了，在decode多转base64。没事了，感谢
