### ISSUE TITLE
上传大文件失败

### ISSUE THREAD

**Issue by EF03** [wildfirechat/vue-chat#26]
我看錯誤是引用proto.min.js 請問大概要調整什麼
![image](https://user-images.githubusercontent.com/47837419/163527216-ba6865be-8bf7-4c54-b43e-6355ed220b03.png)

**Comment by imndx** [comment]
demo 上可以复现吗？

**Comment by EF03** [comment]
![image](https://user-images.githubusercontent.com/47837419/163532452-4ef80674-8046-454f-a3ca-6dbfdcf61199.png)
demo 不能使用

**Comment by imndx** [comment]
[web.wildfirechat.cn](web.wildfirechat.cn)

**Comment by EF03** [comment]
Demo 无法使用，点触上传并未有反应
![image](https://user-images.githubusercontent.com/47837419/163749159-4ac28c83-66ae-4356-87f8-f1ec8abdcc5b.png)
我这媒体储存配置"野火Minio"

**Comment by imndx** [comment]
请确认下，你们的代码和下面的是否一致：

https://github.com/wildfirechat/vue-chat/blob/27ea01a43167c8e29b49331b6facc132c4fcbdac/src/wfc/client/wfc.js#L1547-L1556

**Comment by EF03** [comment]
![image](https://user-images.githubusercontent.com/47837419/163763562-6518f5e0-19d9-4a10-94d5-a74c5958bd9d.png)
![image](https://user-images.githubusercontent.com/47837419/163763572-fcf2422e-929f-4229-9248-c6dc1ce5d6c1.png)

**Comment by imndx** [comment]
> ![image](https://user-images.githubusercontent.com/47837419/163763562-6518f5e0-19d9-4a10-94d5-a74c5958bd9d.png) ![image](https://user-images.githubusercontent.com/47837419/163763572-fcf2422e-929f-4229-9248-c6dc1ce5d6c1.png)

升级一下，你们的```getUploadMediaUrl```少一个参数。
