### ISSUE TITLE
微信浏览器（从微信聊天中点击的链接跳转的浏览器）媒体流回调兼容性问题

### ISSUE THREAD

**Issue by Dooley0509** [wildfirechat/vue-chat#27]
1.触发点击事件开启全屏的同时跳转页面（加了5秒延时和不加延时跳转），无法收到流回调；
2.在跳转页面前不开全屏，在跳转页面后（beforCreate、created、mountd）开全屏，无法收到流回调
3.使用点击事件，第一次执行全屏，第二次执行跳转，两次点击非常快速或延时点击第二次都试过，能收到流回调；

拉流端收不到回调，日志没有错误

推流端有错误日志如下：
![b7c3a50f2cb92ce014cc29cd2a9c349](https://user-images.githubusercontent.com/72616676/165967098-18575eac-15f7-456f-98d7-c8b803898932.jpg)

**Comment by imndx** [comment]
微信浏览器支持 iframe 吗？用 demo 能怎么测试？

**Comment by Dooley0509** [comment]
> 伊

用内网穿透，把公网转发到本地调试端口，然后开启VConsole插件，再用微信访问公网地址进行调试。

**Comment by imndx** [comment]
已解决
