### ISSUE TITLE
扫码登录不上

### ISSUE THREAD

**Issue by wuh876** [wildfirechat/vue-chat#28]
![image](https://user-images.githubusercontent.com/17919150/167246160-99cab40d-8fc4-4467-a05d-cd0b2aa503d4.png)

**Comment by imndx** [comment]
是不是将```config.js```里面```APP_SERVER```改了连你们自行部署的服务端了？

**Comment by wuh876** [comment]
是的

**Comment by wuh876** [comment]
怎么解决呢？

**Comment by imndx** [comment]
你好，```vue-chat``` 依赖的```web sdk```是需要付费的，不能只修改```config.js```，还需要替换```web sdk```才能连接你们自己部署的服务。

你们可以申请试用，[具体请看这儿](https://docs.wildfirechat.cn/trial/)

**Comment by wuh876** [comment]
好的，谢谢
