### ISSUE TITLE
音频通话问题

### ISSUE THREAD

**Issue by sxqsfun** [wildfirechat/vue-chat#3]
1. 网页语音主叫,弹出语音通话页面(已允许授权), android端点击接听按钮后, 网页端语音页面会直接关闭.<br/>
2. android端语音主叫, 网页端弹出语音页面, 接听后, 语音界面还在, 但是通话没有声音.(已按页面提示授权)<br/>

**Comment by imndx** [comment]
1. 请先阅读以下[AV README](https://github.com/wildfirechat/vue-chat/blob/master/src/wfc/av/internal/README.MD)，确保音视频SDK和手机端匹配。
2. 如果问题依然存在，请提供音视频通话窗口的控制台日志。

**Comment by sxqsfun** [comment]
speaker、microphone、webcam检测结果分别为：true , true, true，如果不全为true，请检查硬件设备是否正常，否则通话可能存在异常
avenginekitproxy.js?258e:472 location Location {ancestorOrigins: DOMStringList, href: "http://localhost:8080/#/home", origin: "http://localhost:8080", protocol: "http:", host: "localhost:8080", …}
avenginekitproxy.js?258e:554 process queued event {__ob__: Observer}
avenginekitproxy.js?258e:101 to send voip message CallStartMessageContent {type: 400, mentionedType: 0, mentionedTargets: Array(0), extra: undefined, pushContent: undefined, …}
avenginekitproxy.js?258e:103 delta -302
proto.min.js?026b:1 message prepared 130 n {low: -270914415, high: 377, unsigned: false} Message {conversation: Conversation, from: "2Zv737EE", content: e, messageContent: CallStartMessageContent, messageId: 130, …}
proto.min.js?026b:1 onPrepared Message {…}
proto.min.js?026b:1 _sendMessageInternal 1
ConversationView.vue?ab48:514 conversationView updated true
proto.min.js?026b:1 publish response
proto.min.js?026b:1 publish error code  MS 0
proto.min.js?026b:1 _sendMessageInternal result 0
proto.min.js?026b:1 on push RCN
proto.min.js?026b:1 pull recv n {low: -249560819, high: 52806307, unsigned: false}
proto.min.js?026b:1 publish response
proto.min.js?026b:1 publish error code  RCP 0
proto.min.js?026b:1 pull recv result e {delivery: Array(1), current: n, head: n}
proto.min.js?026b:1 on push MN
proto.min.js?026b:1 to pull user messages 0
proto.min.js?026b:1 pull user messages, type: 0, head: 226801365632942351, msgHead: 226801365632942348, chatroomMsgHead: 0
proto.min.js?026b:1 publish response
proto.min.js?026b:1 publish error code  MP 0
proto.min.js?026b:1 pull user messages response 0
avenginekitproxy.js?258e:181 receive voip message 402 227521407886557315 Message {conversation: Conversation, from: "2Zv737EE", content: e, messageContent: CallByeMessageContent, messageId: 0, …}
avenginekitproxy.js?258e:181 receive voip message 401 227521578101899395 Message {conversation: Conversation, from: "Dr8VEVss", content: e, messageContent: CallAnswerMessageContent, messageId: 0, …}
proto.min.js?026b:1 to pull user messages 0
proto.min.js?026b:1 local message is up to date n {low: -249560817, high: 52806307, unsigned: false} n {low: -249560817, high: 52806307, unsigned: false} false undefined undefined false
proto.min.js?026b:1 on push MN
proto.min.js?026b:1 to pull user messages 0
proto.min.js?026b:1 pull user messages, type: 0, head: 226801365632942352, msgHead: 226801365632942351, chatroomMsgHead: 0
proto.min.js?026b:1 publish response
proto.min.js?026b:1 publish error code  MP 0
proto.min.js?026b:1 pull user messages response 0
avenginekitproxy.js?258e:181 receive voip message 402 227521578871554179 Message {conversation: Conversation, from: "Dr8VEVss", content: e, messageContent: CallByeMessageContent, messageId: 0, …}
proto.min.js?026b:1 to pull user messages 0
proto.min.js?026b:1 local message is up to date n {low: -249560816, high: 52806307, unsigned: false} n {low: -249560816, high: 52806307, unsigned: false} false undefined undefined false
avenginekitproxy.js?258e:101 to send voip message CallByeMessageContent {type: 402, mentionedType: 0, mentionedTargets: Array(0), extra: undefined, pushContent: undefined, …}
avenginekitproxy.js?258e:103 delta -302
proto.min.js?026b:1 onPrepared null
proto.min.js?026b:1 _sendMessageInternal 1
proto.min.js?026b:1 publish response
proto.min.js?026b:1 publish error code  MS 0
proto.min.js?026b:1 _sendMessageInternal result 0
proto.min.js?026b:1 on push RCN
proto.min.js?026b:1 pull recv n {low: -249560818, high: 52806307, unsigned: false}
proto.min.js?026b:1 publish response
proto.min.js?026b:1 publish error code  RCP 0
proto.min.js?026b:1 pull recv result e {delivery: Array(1), current: n, head: n}
avenginekitproxy.js?258e:520 onVoipWindowClose

**Comment by sxqsfun** [comment]
上面是控制台日志.<br/>
我是在笔记本上插着耳机测试的. 浏览器是 chromium.

**Comment by imndx** [comment]
请把Android端的日志也附上，上面的日志看起来是web端收到挂断消息。

另外，确认下Android端和web端所使用的音视频SDK是否一致。

> 1. 请先阅读以下[AV README](https://github.com/wildfirechat/vue-chat/blob/master/src/wfc/av/internal/README.MD)，确保音视频SDK和手机端匹配。
> 2. 如果问题依然存在，请提供音视频通话窗口的控制台日志。

**Comment by imndx** [comment]
no response.
