### ISSUE TITLE
mac clientId 生成的规则是什么，有没有像windows生成的debugChat.ini，详细看正文

### ISSUE THREAD

**Issue by yizhihuamao** [wildfirechat/vue-chat#30]
windows下有这个
![image](https://user-images.githubusercontent.com/74225715/174264070-384255f2-e6c9-470f-9045-34a8ba2a56de.png)
![image](https://user-images.githubusercontent.com/74225715/174264102-2cbf7803-a9da-4dec-9624-6321574c1114.png)

mac在哪里？或者mac的生成规则是什么，能否让我们自定义生成规则，或告知更改的方法
<img width="629" alt="image" src="https://user-images.githubusercontent.com/74225715/174264297-dfb2daf0-f535-40f6-8458-8d49a899ad18.png">

**Comment by imndx** [comment]
```std::string GetClientId() {
    static std::string clientId;
    if (!clientId.empty()) {
      return clientId;
    }

    NSString *savedId = [[NSUserDefaults standardUserDefaults] objectForKey:@"mars:osx:clientId"];
    if (savedId.length == 0) {
    savedId = [NSUUID UUID].UUIDString;
    [[NSUserDefaults standardUserDefaults] setObject:savedId forKey:@"mars:osx:clientId"];
    [[NSUserDefaults standardUserDefaults] synchronize];
    }
    clientId = [savedId cStringUsingEncoding:NSUTF8StringEncoding];
    return clientId;
}
