### ISSUE TITLE
扫码登录的时候后台说会话没有验证怎么改？

### ISSUE THREAD

**Issue by leishenglong** [wildfirechat/vue-chat#31]
请问扫码登录的时候后台说会话没有验证怎么改？

**Comment by imndx** [comment]
你好，请先确认下：

web SDK 是需要付费的，且依赖于专业版 im-server。
确认上面问题之后，如果还是有问题，请提供下日志。

另外，web sdk 和专业版 im-server，都可以申请试用，具体请看这儿。

**Comment by leishenglong** [comment]
开源版的 im-server也不能用吗？

**Comment by imndx** [comment]
> 开源版的 im-server也不能用吗？

是的，开源的社区版 im-server 不支持 web 端接入。
