### ISSUE TITLE
有考虑用vue3重构吗?

### ISSUE THREAD

**Issue by cfmj** [wildfirechat/vue-chat#33]
项目架构似乎有些旧了,api接口没有统一管理  
如果相同接口在多个页面调用,修改这个接口时就要同时修改多个页面

希望用vue3重构,祝好

**Comment by imndx** [comment]
你好

1. api 接口版本统一管理，已处理完成，近期会合并代码。
2. 关于用```vue3```重构问题，目前还没有相关计划

**Comment by cfmj** [comment]
好的 感谢回复
