### ISSUE TITLE
文档中说的字段在config.js 里面没有啊

### ISSUE THREAD

**Issue by NewNameArk** [wildfirechat/vue-chat#36]
https://docs.wildfirechat.cn/faq/web.html  下面1.1 提到的 WEB_APP_ID和WEB_APP_KEY  在config.js中没有啊

**Comment by imndx** [comment]
你好，这两个字段废弃了，文档稍后更新一下问题。

直接替换 ```proto.min.js```文件，即可

**Comment by NewNameArk** [comment]
好的 3Q
