### ISSUE TITLE
SDK  报错 TypeError: Cannot read properties of undefined (reading 'delete')

### ISSUE THREAD

**Issue by cfmj** [wildfirechat/vue-chat#40]
![1667809782996](https://user-images.githubusercontent.com/33464433/200262079-93b25172-7d42-4c53-b611-afc801950494.png)

**Comment by imndx** [comment]
请问这个问题是什么情况下出现的？

请微信添加```wfchat``，我们了解下情况

**Comment by imndx** [comment]
no response
