### ISSUE TITLE
音视频通话消息,字段undefined导致显示不准确

### ISSUE THREAD

**Issue by cfmj** [wildfirechat/vue-chat#43]
![image](https://user-images.githubusercontent.com/33464433/203715711-022842fb-15ef-4003-9a17-a4fdfb1f0033.png)

**Comment by cfmj** [comment]
切换用户后 出现音视频通话消息部分丢失  
![953a8aa75a2120e68b4c6cb4c889be7](https://user-images.githubusercontent.com/33464433/203717777-74764fae-c2e9-40d5-8467-914f09f5b1a3.jpg)

**Comment by imndx** [comment]
实际有接通
app删除后重装 显示未接通 (可能是消息字段undefined导致显示不准确?)

------------------

由于音视频通话相关消息的状态是存在本地的，卸载重装之后，消息状态会丢失，故显示错误。

**Comment by cfmj** [comment]
> 实际有接通 app删除后重装 显示未接通 (可能是消息字段undefined导致显示不准确?)
> 
> 由于音视频通话相关消息的状态是存在本地的，卸载重装之后，消息状态会丢失，故显示错误。

所以是设计如此吗? 有更改的打算吗

**Comment by imndx** [comment]
> > 实际有接通 app删除后重装 显示未接通 (可能是消息字段undefined导致显示不准确?)
> > 由于音视频通话相关消息的状态是存在本地的，卸载重装之后，消息状态会丢失，故显示错误。
> 
> 所以是设计如此吗? 有更改的打算吗

目前没有修改的打算，状态未知时，可以尝试显示比较中性的提示。
