### ISSUE TITLE
群聊保存通讯录不回显

### ISSUE THREAD

**Issue by cfmj** [wildfirechat/vue-chat#47]
![image](https://user-images.githubusercontent.com/33464433/210333631-864fad89-bf16-434b-9c39-5928c3f12207.png)
实际已经保存到通讯录

**Comment by imndx** [comment]
无法复现，请用 [在线 demo](https://web.wildfirechat.cn/) 测试下

**Comment by cfmj** [comment]
https://user-images.githubusercontent.com/33464433/210359925-6ae5c74c-2e10-4143-84b2-d0a37cba1886.mp4

**Comment by cfmj** [comment]
不是所有群聊 都能复现

**Comment by imndx** [comment]
能看下出现这问题的时候，控制台有没有什么报错日志不？

**Comment by cfmj** [comment]
复现不是很稳定 如果需要提供账号的话,告诉我怎么可以联系你们 
这是控制台日志
![image](https://user-images.githubusercontent.com/33464433/210728081-267a776d-c417-497b-920a-5866df257e44.png)

**Comment by imndx** [comment]
可以微信联系：wfchat
