### ISSUE TITLE
创建群聊失败

### ISSUE THREAD

**Issue by cfmj** [wildfirechat/vue-chat#48]
![1672739822818](https://user-images.githubusercontent.com/33464433/210334769-1e5cb66a-b199-4b6e-877e-3cf8683696b1.png)

**Comment by cfmj** [comment]
发送图片 我是先上传自己的服务器再使用remoteUrl    
这样的话创建群聊要怎么弄

**Comment by imndx** [comment]
可以直接调用 ```wfc.createGroup``` 接口
