### ISSUE TITLE
打开voip调试模式

### ISSUE THREAD

**Issue by 871263000** [wildfirechat/vue-chat#49]
打开voip调试模式时，voip window不会自动关闭，方便分析控制台日志，需要手动关闭

ENABLE_VOIP_DEBUG_MODE = true; 

打开voip调试还是会自动关闭页面。  
域名后面有有层级有关系吗？

**Comment by 871263000** [comment]
而且主动发起会自动关闭页面，  别人给web端发起语音不会关闭，但是接通就会挂断。  我用http://localhost:8013/这个域名没有问题， 换成线上域名就会出现这种情况

**Comment by imndx** [comment]
是小写的，

如果： ```localStorage``` 里面有 ```enable_voip_debug``` ，就不会自动关闭，没有就会自动关闭。调试完毕，需要将该项删除

**Comment by 871263000** [comment]
我手动加了，  还是会自动关闭。  enable_voip_debug这个参数我本地全局搜了一下llocalStorage.getItem("enable_voip_debug")这个只有getItem. 并没有setItem.     别人给web端发起语音不会关闭，但是接通就会关闭。我用http://localhost:8013/这个域名没有问题， 换成线上域名就会出现这种情况

**Comment by 871263000** [comment]
我手动加了，  还是会自动关闭。  enable_voip_debug这个参数我本地全局搜了一下llocalStorage.getItem("enable_voip_debug")这个只有getItem. 并没有setItem.     别人给web端发起语音不会关闭，但是接通就会关闭。我用http://localhost:8013/这个域名没有问题， 换成线上域名就会出现这种情况

**Comment by imndx** [comment]
```http```站点，非```localhost```访问的时候，不支持```webrtc```的；使用```https```访问站点

**Comment by imndx** [comment]
那现在是什么

> 我手动加了， 还是会自动关闭。 enable_voip_debug这个参数我本地全局搜了一下llocalStorage.getItem("enable_voip_debug")这个只有getItem. 并没有setItem. 别人给web端发起语音不会关闭，但是接通就会关闭。我用[http://localhost:8013/这个域名没有问题，](http://localhost:8013/%E8%BF%99%E4%B8%AA%E5%9F%9F%E5%90%8D%E6%B2%A1%E6%9C%89%E9%97%AE%E9%A2%98%EF%BC%8C) 换成线上域名就会出现这种情况

没有 ```setItem```的，只会```getItem```判断是否关闭音视频通话窗口。

现在具体什么问题，请贴下控制台日志看看

**Comment by 871263000** [comment]
web端发起语音不会关闭音视频通话窗口，但是接通就会关闭。我用[http://localhost:8013/这个域名没有问题, 换成线上域名就会出现关闭音视频通话窗口. 使用https访问站点,   控制台日志看不了。 直接就关闭窗口了。  enable_voip_debug这个设置了也不起作用
