### ISSUE TITLE
发送截图有时候发送失败

### ISSUE THREAD

**Issue by 871263000** [wildfirechat/vue-chat#50]
从excel表格里复制出来的图片，  发送会失败！就比如下面这张图片就会发送失败！
![图片1](https://user-images.githubusercontent.com/15119155/211753325-325c392a-3340-490b-b173-65dd7fd856b8.png)
下图是错误信息
<img width="795" alt="image" src="https://user-images.githubusercontent.com/15119155/211753635-2891d5d0-ee4b-4e1c-85a0-93bb152dd784.png">
图片地址已经生成 https://omso2o.com/409-1-1673424999-21896285.jpg  就是发送失败！

**Comment by 871263000** [comment]
<img width="654" alt="image" src="https://user-images.githubusercontent.com/15119155/211961150-41e35e93-c450-4b4c-a1cc-cd5d9c673549.png">

如果file.size < 15 * 1024 就会发送不过去 报错，  特别是截图。   电脑分辨率小的。  就容易file.size就打不到这个值

**Comment by imndx** [comment]
> 如果file.size < 15 * 1024 就会发送不过去 报错， 特别是截图。 电脑分辨率小的。 就容易file.size就打不到这个值

上面的意思是，图片文件小于 15k 的时候，就不生成缩略图了，直接发送没缩略图的图片消息

**Comment by 871263000** [comment]
不行， 会报错。  你试一下。iThumbnail.length undefined。iThumbnail.split(',')[1] 这个可能也会报错。  不会发送
