### ISSUE TITLE
发送的图片在苹果app上看不到。  点击之后可以看到

### ISSUE THREAD

**Issue by 871263000** [wildfirechat/vue-chat#53]
![](https://omso2o.com/409-1-1673599670-86038883.jpg)

![](https://omso2o.com/409-1-1673599419-34044170.jpg)
这两张都不行
好多图片从web端发送， 苹果app不能显示图片。  点击放大可以看到。  从苹果app发送就没有问题

**Comment by imndx** [comment]
@heavyrain2012

**Comment by heavyrain2012** [comment]
这是因为消息不正确导致的。请确保web端发送图片消息正确生成缩略图。

**Comment by heavyrain2012** [comment]
iOS加了一个默认缩略图，当没有缩略图时，会显示默认的这个缩略图，你们也可以改成其他的默认缩略图。请参考提交 https://github.com/wildfirechat/ios-chat/commit/bfad0c3966616148b6829926ec476cd84cc79959

**Comment by 871263000** [comment]
web端能不能没有缩略图，就把原图当缩略图。不要让缩略图为空，这样更好一点

**Comment by heavyrain2012** [comment]
这个不太好，有可能图片1MB或者更大，加载会很慢，会导致卡顿等问题

**Comment by 871263000** [comment]
刚开始只有很小图片不能生成缩略图发送不了，   我的意思就是那些很小的不能生成缩略图的把原图当成缩略图。  其他不变。

**Comment by 871263000** [comment]
刚开始只有很小图片不能生成缩略图发送不了，   我的意思就是那些很小的不能生成缩略图的把原图当成缩略图。  其他不变。

**Comment by imndx** [comment]
> 刚开始只有很小图片不能生成缩略图发送不了， 我的意思就是那些很小的不能生成缩略图的把原图当成缩略图。 其他不变。

这个你们可以自己这么做，具体代码在这儿 https://github.com/wildfirechat/vue-chat/blob/b5f9104e65bfa2e60dfca65f9937917971803a42/src/store.js#L851
