### ISSUE TITLE
关于跳转到未读消息第一条功能

### ISSUE THREAD

**Issue by Acy-zh** [wildfirechat/vue-chat#60]
请问可以直接跳到第一条未读消息吗，如何拿到未读消息数，是否可以根据未读消息数进行判断？

**Comment by imndx** [comment]
可以的，大概步骤是：

1. `ConversationInfo` 里面的`unreadCount`包含未读消息数量
2. 获取会话消息列表的时候，获取比未读数大一些的消息数，`demo`是在`store#_loadCurrentConversationMessages`里面处理获取会话的消息列表的，默认获取的是 `20` 条，这儿可以判断下是否有未读消息，如果有未读消息的话，就传入比未读数大一些的数进行会话消息列表的获取
3. 会话消息列表里面渲染的消息列表，每个消息项的`key`都是`messageId`，可以写个方法，找到第一条未读消息的`messageId`，然后根据消息的`messageId`找到对应的`element`，然后滚动到该`element`

> 
如何找到第一条未读消息？

消息列表是有序的，从旧到新，第一条`status === 5`的消息就是第一条未读消息

**Comment by Acy-zh** [comment]
好的 非常感谢

**Comment by imndx** [comment]
还有个思路
1. `getFirstUnreadMessage` 获取第一条未读消息
2. 进入会话界面，在右上角展示 `有 xxx 条未读消息的提示`，这儿需要注意的是，点击会话列表时，现在的 UI 实现，会清未读数，需要提前记录一下未读数。
3. 点击 `有 xxx 条未读消息时`，进行循环加载历史消息，直至加载到第一条未读消息
