### ISSUE TITLE
外部挂断语音

### ISSUE THREAD

**Issue by gushuting123** [wildfirechat/vue-chat#68]
vue语音窗口不管是 新页面打开 还是 iframe打开，都需要在外部控制挂断（非single页面挂断），麻烦帮忙写一个方法

**Comment by imndx** [comment]
`avenginekitproxy.js`里面有两个方法：`emitToVoip`和`listenVoipEvent`

1. 在音视频通话窗口，即`Single.vue`里面，通过`listenVoipEvent`监听请求挂断事件，收到挂断事件时，执行`session.hangup()`进行挂断
2. 需要从主窗口挂断音视频通话时，通过`emitToVoip`发送请求挂断事件

下面是参考代码：
```
// HomePage.vue

avenginekitproxy.emitToVoip('hangupNow', {
// 可以传一些参数
})

// Single.vue

avenginekitproxy.listenVoipEvent('hangupNow',  (event, args) => {
    this.session.hangup();
   // ....
}

```
