### ISSUE TITLE
对方在己方是群主的群里设置了群昵称后，在单聊和通讯录里，对方名字会显示成群昵称

### ISSUE THREAD

**Issue by zenggong965** [wildfirechat/vue-chat#71]
己方是群主，对方在群里设置群昵称后，当己方在会话列表点中这个群，在会话列表和通讯录里，这个好友的名字就会显示成群昵称
![image](https://github.com/wildfirechat/vue-chat/assets/11338629/b6830a82-0cb7-466d-a036-244f85ca0cc7)
![image](https://github.com/wildfirechat/vue-chat/assets/11338629/9b1543ed-d35e-4ecc-9671-f7b6fb070856)

**Comment by imndx** [comment]
请用最新 demo 测试一下，这个问题应当修复了的。

**Comment by zenggong965** [comment]
> 请用最新 demo 测试一下，这个问题应当修复了的。

@imndx 用了官网的网页版（https://wildfirechat.cn/download/），还是有这个问题
![image](https://github.com/wildfirechat/vue-chat/assets/11338629/af43ec40-c046-40ab-9989-f550414d0ec3)
