### ISSUE TITLE
多选消息里包含图片并且转发给多个目标会话会失败

### ISSUE THREAD

**Issue by zenggong965** [wildfirechat/vue-chat#74]
我们近期升级了web sdk，报错里有sdk相关信息
我们的测试和生产环境都复现了
问题截图和控制台截图请看附件
[多选消息里包含图片并且转发给多个目标会话会失败.pdf](https://github.com/wildfirechat/vue-chat/files/12414748/default.pdf)

发现一个复现路径：
勾选3条消息，分别按顺序是图片、文字、图片，图片得是不同的图片
转发给多个会话，2个以上的会话
转发的3条消息都会失败

**Comment by imndx** [comment]
已修复，请更新专业版`im-server`进行测试。
