### ISSUE TITLE
搜索未设置头像的用户会显示破图

### ISSUE THREAD

**Issue by zenggong965** [wildfirechat/vue-chat#77]
![image](https://github.com/wildfirechat/vue-chat/assets/11338629/be8eafd8-9697-49bd-8fb6-312f4adc0f16)

**Comment by zenggong965** [comment]
@imndx 好像还有问题，用的是今天的官网demo，用ctrl+shift+R强刷新过
![image](https://github.com/wildfirechat/vue-chat/assets/11338629/ed3575f1-ef67-4cad-ae67-e9434f3796ef)

**Comment by imndx** [comment]
我用线上测试了下，是下面这种情况
<img width="468" alt="image" src="https://github.com/wildfirechat/vue-chat/assets/34434072/402c8411-54cf-412b-8d89-050c04e78866">

**Comment by zenggong965** [comment]
@imndx  我用无痕模式也这样，附控制台截图
![image](https://github.com/wildfirechat/vue-chat/assets/11338629/ee7bc040-4c18-4a0a-b57c-9b52322569d6)

**Comment by imndx** [comment]
你搜索`123`，看看有没有我上面贴图那种自动生成的头像。

我`inspect`看了下，你搜出来的这几个用户，都设置了默认头像，`https://avatars.io/gravatar/6OEk6koo`，但这个默认头像停服了，所以看起来是破图

**Comment by imndx** [comment]
已经处理`https://avatars.io`异常头像问题，请重新搜索测试下。

<img width="479" alt="image" src="https://github.com/wildfirechat/vue-chat/assets/34434072/4b7d1acf-baaf-410c-8d9b-5c7179479f54">
