### ISSUE TITLE
在一个群里设置的群昵称也显示到的别的群

### ISSUE THREAD

**Issue by zenggong965** [wildfirechat/vue-chat#78]
### 步骤
在A群里设置群昵称
打开B群的群设置页面

### 表现
能看到自己在A群设置的群昵称，手机端是正常的，应该是网页版的显示问题

### 预期结果
看不到自己在A群设置的群昵称，也就是群昵称只在所属的群里生效

在A群设置了群昵称
![image](https://github.com/wildfirechat/vue-chat/assets/11338629/63fe3145-49b4-4f84-bb8b-41f3dc4c4a48)

在B群也显示了同样的群昵称
![image](https://github.com/wildfirechat/vue-chat/assets/11338629/85cdf9a6-b930-42e1-97d9-b40fafbe6e50)

**Comment by imndx** [comment]
最新demo，还存在这问题吗？

**Comment by zenggong965** [comment]
> 最新demo，还存在这问题吗？

@imndx 这就是用当天最新的demo测试的，我刚才又试了一下，还是有这个问题 https://web.wildfirechat.cn/#/
