### ISSUE TITLE
创建群聊或者群内添加/移除超长用户名的用户时，确认页发送/添加/移除按钮被遮挡

### ISSUE THREAD

**Issue by FelicityCiao** [wildfirechat/vue-chat#83]
**操作：**
在列表中勾选超过16位中文用户名的用户，

**问题表现：**
右下角“发送”、“移除”与“添加”按钮被向右侧顶出。
如果名称为20位则完全遮挡，无法成功操作创建、添加或移除群成员。

勾选前按钮正常
勾选后按钮被顶出遮挡

**预期：**
勾选长用户名的用户不影响群员管理操作。

**Comment by FelicityCiao** [comment]
![勾选前](https://github.com/wildfirechat/vue-chat/assets/5611610/9e6d6974-244e-4812-843a-a51fe5489784)
勾选后：
![勾选后](https://github.com/wildfirechat/vue-chat/assets/5611610/4506cefe-2a5c-4f20-88e0-9a34a795144e)

**Comment by FelicityCiao** [comment]
验证了一下不行。
![#83-reopen01](https://github.com/wildfirechat/vue-chat/assets/5611610/ee67d721-a5b5-447c-8f07-eeb329a9cff4)
勾选时

**Comment by imndx** [comment]
请重新测试下：[19db611](https://github.com/wildfirechat/vue-chat/commit/19db6119f8a532f98078854e99a4602ccad1c4a8)
