### ISSUE TITLE
Error: Cannot call .tap() on a plugin that has not yet been defined. Call plugin('preload').use(<Plugin>) first

### ISSUE THREAD

**Issue by bad-pear** [wildfirechat/vue-chat#84]
你好，我npm install成功之后，npm run serve 出现启动失败出现如下错误：
 INFO  Starting development server...
 ERROR  Error: Cannot call .tap() on a plugin that has not yet been defined. Call plugin('preload').use(<Plugin>) first.
Error: Cannot call .tap() on a plugin that has not yet been defined. Call plugin('preload').use(<Plugin>) first.
    at Object.tap (D:\work\im\gitee\vue-chat\node_modules\webpack-chain\src\Plugin.js:26:15)
    at chainWebpack (D:\work\im\gitee\vue-chat\vue.config.js:25:34)
    at D:\work\im\gitee\vue-chat\node_modules\@vue\cli-service\lib\Service.js:268:40
    at Array.forEach (<anonymous>)
    at Service.resolveChainableWebpackConfig (D:\work\im\gitee\vue-chat\node_modules\@vue\cli-service\lib\Service.js:268:26)
    at Service.resolveWebpackConfig (D:\work\im\gitee\vue-chat\node_modules\@vue\cli-service\lib\Service.js:272:48)
    at PluginAPI.resolveWebpackConfig (D:\work\im\gitee\vue-chat\node_modules\@vue\cli-service\lib\PluginAPI.js:132:25)
    at serve (D:\work\im\gitee\vue-chat\node_modules\@vue\cli-service\lib\commands\serve.js:79:31)
    at Service.run (D:\work\im\gitee\vue-chat\node_modules\@vue\cli-service\lib\Service.js:262:12)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)

我想问下，应该修改哪里？能够启动成功

![图片](https://github.com/wildfirechat/vue-chat/assets/17894730/3b7c361f-28c5-4a0e-8ece-540d87764c46)

**Comment by bad-pear** [comment]
node 14.18.0
npm : 6.14.x

**Comment by imndx** [comment]
你这样试下：
1. 删除`node_modules`目录
2. `npm ci --verbose --registry=https://mirrors.huaweicloud.com/repository/npm/`


PS:  我本地的node 是 `v14.18.1`

**Comment by bad-pear** [comment]
用华为云的这个，还在下载，下的我怀疑人生

**Comment by bad-pear** [comment]
还是不行。 Error: Cannot call .tap() on a plugin that has not yet been defined. Call plugin('preload').use(<Plugin>) first

**Comment by bad-pear** [comment]
好像同环境没有关系吧。是配置有问题吗

**Comment by bad-pear** [comment]
我把node也改成 同你一样了。14.18.1

**Comment by imndx** [comment]
你改了什么吗？还是说什么都不改，直接跑 demo 就有这问题？

**Comment by bad-pear** [comment]
下载下来就安装，用npm install ， npm  audit fix  , npm audit fix --force命令。然后npm run serve
又试了下14.18.1版本，然后删除库，然后使用华为云的那个命令，下载好之后，npm run serve也不行。
在master版本

**Comment by imndx** [comment]
> 下载下来就安装，用npm install ， npm audit fix , npm audit fix --force命令。然后npm run serve 又试了下14.18.1版本，然后删除库，然后使用华为云的那个命令，下载好之后，npm run serve也不行。 在master版本

不执行`npm install`
1. 删除`node_modules`目录
2. `npm ci --verbose --registry=https://mirrors.huaweicloud.com/repository/npm/`
3. `npm run serve`

**Comment by bad-pear** [comment]
对的，就是这个搞得，后面几遍。不行呀

**Comment by bad-pear** [comment]
我再试一遍

**Comment by bad-pear** [comment]
我把项目删除，使用命令npm ci --verbose --registry=https://mirrors.huaweicloud.com/repository/npm/
出现下面这个报错
![图片](https://github.com/wildfirechat/vue-chat/assets/17894730/2ce89353-fe40-4ad0-817d-7bd2dcbc70dd)

**Comment by imndx** [comment]
我们更新了`package-lock.json`，请重新试下

**Comment by bad-pear** [comment]
ok, 能run了。我的好大哥。请求地址是http://localhost:5000/  吗。请求失败是因为下面这个启动之后的报错吗
![图片](https://github.com/wildfirechat/vue-chat/assets/17894730/969c30c8-bd74-4b54-aeba-4fe6ad5e49ef)

**Comment by bad-pear** [comment]
error  in ./src/ui/common/AlertView.vue

Module Error (from ./node_modules/vue-loader/lib/index.js):


Vue packages version mismatch:

- vue@2.6.14 (D:\work\im\gitee\vue-chat\node_modules\vue\dist\vue.runtime.common.js)
- vue-template-compiler@2.6.12 (D:\work\im\gitee\vue-chat\node_modules\vue-template-compiler\package.json)

This may cause things to work incorrectly. Make sure to use the same version for both.
If you are using vue-loader@>=10.0, simply update vue-template-compiler.
If you are using vue-loader@<10.0 or vueify, re-installing vue-loader/vueify should bump vue-template-compiler to the latest.


 @ ./src/ui/common/Alert.js 1:0-40 27:23-32
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://192.168.2.195:8013&sockPath=/sockjs-node (webpack)/hot/dev-server.js ./src/main.js

 error  in ./src/App.vue

Module Error (from ./node_modules/vue-loader/lib/index.js):


Vue packages version mismatch:

- vue@2.6.14 (D:\work\im\gitee\vue-chat\node_modules\vue\dist\vue.runtime.common.js)
- vue-template-compiler@2.6.12 (D:\work\im\gitee\vue-chat\node_modules\vue-template-compiler\package.json)

This may cause things to work incorrectly. Make sure to use the same version for both.
If you are using vue-loader@>=10.0, simply update vue-template-compiler.
If you are using vue-loader@<10.0 or vueify, re-installing vue-loader/vueify should bump vue-template-compiler to the latest.


 @ ./src/main.js 8:0-28 131:13-16
 @ multi (webpack)-dev-server/client?http://192.168.2.195:8013&sockPath=/sockjs-node (webpack)/hot/dev-server.js ./src/main.js

 error  in ./src/ui/main/MessagePage.vue

Module Error (from ./node_modules/vue-loader/lib/index.js):


Vue packages version mismatch:

- vue@2.6.14 (D:\work\im\gitee\vue-chat\node_modules\vue\dist\vue.runtime.common.js)
- vue-template-compiler@2.6.12 (D:\work\im\gitee\vue-chat\node_modules\vue-template-compiler\package.json)

This may cause things to work incorrectly. Make sure to use the same version for both.
If you are using vue-loader@>=10.0, simply update vue-template-compiler.
If you are using vue-loader@<10.0 or vueify, re-installing vue-loader/vueify should bump vue-template-compiler to the latest.


 @ ./src/routers.js 17:0-52 77:13-24
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://192.168.2.195:8013&sockPath=/sockjs-node (webpack)/hot/dev-server.js ./src/main.js

 error  in ./src/ui/main/ConversationPage.vue

Module Error (from ./node_modules/vue-loader/lib/index.js):


Vue packages version mismatch:

- vue@2.6.14 (D:\work\im\gitee\vue-chat\node_modules\vue\dist\vue.runtime.common.js)
- vue-template-compiler@2.6.12 (D:\work\im\gitee\vue-chat\node_modules\vue-template-compiler\package.json)

This may cause things to work incorrectly. Make sure to use the same version for both.
If you are using vue-loader@>=10.0, simply update vue-template-compiler.
If you are using vue-loader@<10.0 or vueify, re-installing vue-loader/vueify should bump vue-template-compiler to the latest.


 @ ./src/routers.js 3:0-58 28:15-31
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://192.168.2.195:8013&sockPath=/sockjs-node (webpack)/hot/dev-server.js ./src/main.js

 error  in ./src/ui/main/MultimediaPreviewPage.vue

Module Error (from ./node_modules/vue-loader/lib/index.js):


Vue packages version mismatch:

- vue@2.6.14 (D:\work\im\gitee\vue-chat\node_modules\vue\dist\vue.runtime.common.js)
- vue-template-compiler@2.6.12 (D:\work\im\gitee\vue-chat\node_modules\vue-template-compiler\package.json)

This may cause things to work incorrectly. Make sure to use the same version for both.
If you are using vue-loader@>=10.0, simply update vue-template-compiler.
If you are using vue-loader@<10.0 or vueify, re-installing vue-loader/vueify should bump vue-template-compiler to the latest.


 @ ./src/routers.js 18:0-72 81:13-34
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://192.168.2.195:8013&sockPath=/sockjs-node (webpack)/hot/dev-server.js ./src/main.js

 error  in ./src/ui/main/MessageHistoryPage.vue

Module Error (from ./node_modules/vue-loader/lib/index.js):


Vue packages version mismatch:

- vue@2.6.14 (D:\work\im\gitee\vue-chat\node_modules\vue\dist\vue.runtime.common.js)
- vue-template-compiler@2.6.12 (D:\work\im\gitee\vue-chat\node_modules\vue-template-compiler\package.json)

This may cause things to work incorrectly. Make sure to use the same version for both.
If you are using vue-loader@>=10.0, simply update vue-template-compiler.
If you are using vue-loader@<10.0 or vueify, re-installing vue-loader/vueify should bump vue-template-compiler to the latest.


 @ ./src/routers.js 13:0-62 85:13-31
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://192.168.2.195:8013&sockPath=/sockjs-node (webpack)/hot/dev-server.js ./src/main.js

 error  in ./src/ui/main/HomePage.vue

Module Error (from ./node_modules/vue-loader/lib/index.js):


Vue packages version mismatch:

- vue@2.6.14 (D:\work\im\gitee\vue-chat\node_modules\vue\dist\vue.runtime.common.js)
- vue-template-compiler@2.6.12 (D:\work\im\gitee\vue-chat\node_modules\vue-template-compiler\package.json)

This may cause things to work incorrectly. Make sure to use the same version for both.
If you are using vue-loader@>=10.0, simply update vue-template-compiler.
If you are using vue-loader@<10.0 or vueify, re-installing vue-loader/vueify should bump vue-template-compiler to the latest.


 @ ./src/routers.js 1:0-42 24:13-21
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://192.168.2.195:8013&sockPath=/sockjs-node (webpack)/hot/dev-server.js ./src/main.js

 error  in ./src/ui/main/CompositeMessagePage.vue

Module Error (from ./node_modules/vue-loader/lib/index.js):


Vue packages version mismatch:

- vue@2.6.14 (D:\work\im\gitee\vue-chat\node_modules\vue\dist\vue.runtime.common.js)
- vue-template-compiler@2.6.12 (D:\work\im\gitee\vue-chat\node_modules\vue-template-compiler\package.json)

This may cause things to work incorrectly. Make sure to use the same version for both.
If you are using vue-loader@>=10.0, simply update vue-template-compiler.
If you are using vue-loader@<10.0 or vueify, re-installing vue-loader/vueify should bump vue-template-compiler to the latest.


 @ ./src/routers.js 12:0-66 73:13-33
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://192.168.2.195:8013&sockPath=/sockjs-node (webpack)/hot/dev-server.js ./src/main.js

 error  in ./src/ui/main/ContactPage.vue

Module Error (from ./node_modules/vue-loader/lib/index.js):


Vue packages version mismatch:

- vue@2.6.14 (D:\work\im\gitee\vue-chat\node_modules\vue\dist\vue.runtime.common.js)
- vue-template-compiler@2.6.12 (D:\work\im\gitee\vue-chat\node_modules\vue-template-compiler\package.json)

This may cause things to work incorrectly. Make sure to use the same version for both.
If you are using vue-loader@>=10.0, simply update vue-template-compiler.
If you are using vue-loader@<10.0 or vueify, re-installing vue-loader/vueify should bump vue-template-compiler to the latest.


 @ ./src/routers.js 4:0-48 32:15-26
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://192.168.2.195:8013&sockPath=/sockjs-node (webpack)/hot/dev-server.js ./src/main.js

 error  in ./src/ui/main/LoginPage.vue

Module Error (from ./node_modules/vue-loader/lib/index.js):


Vue packages version mismatch:

- vue@2.6.14 (D:\work\im\gitee\vue-chat\node_modules\vue\dist\vue.runtime.common.js)
- vue-template-compiler@2.6.12 (D:\work\im\gitee\vue-chat\node_modules\vue-template-compiler\package.json)

This may cause things to work incorrectly. Make sure to use the same version for both.
If you are using vue-loader@>=10.0, simply update vue-template-compiler.
If you are using vue-loader@<10.0 or vueify, re-installing vue-loader/vueify should bump vue-template-compiler to the latest.


 @ ./src/routers.js 2:0-44 21:13-22
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://192.168.2.195:8013&sockPath=/sockjs-node (webpack)/hot/dev-server.js ./src/main.js

 error  in ./src/ui/main/fav/FavPage.vue

Module Error (from ./node_modules/vue-loader/lib/index.js):


Vue packages version mismatch:

- vue@2.6.14 (D:\work\im\gitee\vue-chat\node_modules\vue\dist\vue.runtime.common.js)
- vue-template-compiler@2.6.12 (D:\work\im\gitee\vue-chat\node_modules\vue-template-compiler\package.json)

This may cause things to work incorrectly. Make sure to use the same version for both.
If you are using vue-loader@>=10.0, simply update vue-template-compiler.
If you are using vue-loader@<10.0 or vueify, re-installing vue-loader/vueify should bump vue-template-compiler to the latest.


 @ ./src/routers.js 9:0-44 36:15-22
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://192.168.2.195:8013&sockPath=/sockjs-node (webpack)/hot/dev-server.js ./src/main.js

 error  in ./src/ui/main/ConversationFloatPage.vue

Module Error (from ./node_modules/vue-loader/lib/index.js):


Vue packages version mismatch:

- vue@2.6.14 (D:\work\im\gitee\vue-chat\node_modules\vue\dist\vue.runtime.common.js)
- vue-template-compiler@2.6.12 (D:\work\im\gitee\vue-chat\node_modules\vue-template-compiler\package.json)

This may cause things to work incorrectly. Make sure to use the same version for both.
If you are using vue-loader@>=10.0, simply update vue-template-compiler.
If you are using vue-loader@<10.0 or vueify, re-installing vue-loader/vueify should bump vue-template-compiler to the latest.


 @ ./src/routers.js 15:0-68 93:13-34
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://192.168.2.195:8013&sockPath=/sockjs-node (webpack)/hot/dev-server.js ./src/main.js

 error  in ./src/ui/main/setting/SettingPage.vue

Module Error (from ./node_modules/vue-loader/lib/index.js):


Vue packages version mismatch:

- vue@2.6.14 (D:\work\im\gitee\vue-chat\node_modules\vue\dist\vue.runtime.common.js)
- vue-template-compiler@2.6.12 (D:\work\im\gitee\vue-chat\node_modules\vue-template-compiler\package.json)

This may cause things to work incorrectly. Make sure to use the same version for both.
If you are using vue-loader@>=10.0, simply update vue-template-compiler.
If you are using vue-loader@<10.0 or vueify, re-installing vue-loader/vueify should bump vue-template-compiler to the latest.


 @ ./src/routers.js 5:0-56 44:15-26
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://192.168.2.195:8013&sockPath=/sockjs-node (webpack)/hot/dev-server.js ./src/main.js

 error  in ./src/ui/main/ConversationMessageHistoryPage.vue

Module Error (from ./node_modules/vue-loader/lib/index.js):


Vue packages version mismatch:

- vue@2.6.14 (D:\work\im\gitee\vue-chat\node_modules\vue\dist\vue.runtime.common.js)
- vue-template-compiler@2.6.12 (D:\work\im\gitee\vue-chat\node_modules\vue-template-compiler\package.json)

This may cause things to work incorrectly. Make sure to use the same version for both.
If you are using vue-loader@>=10.0, simply update vue-template-compiler.
If you are using vue-loader@<10.0 or vueify, re-installing vue-loader/vueify should bump vue-template-compiler to the latest.


 @ ./src/routers.js 14:0-86 89:13-43
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://192.168.2.195:8013&sockPath=/sockjs-node (webpack)/hot/dev-server.js ./src/main.js

 error  in ./src/ui/voip/Single.vue

Module Error (from ./node_modules/vue-loader/lib/index.js):


Vue packages version mismatch:

- vue@2.6.14 (D:\work\im\gitee\vue-chat\node_modules\vue\dist\vue.runtime.common.js)
- vue-template-compiler@2.6.12 (D:\work\im\gitee\vue-chat\node_modules\vue-template-compiler\package.json)

This may cause things to work incorrectly. Make sure to use the same version for both.
If you are using vue-loader@>=10.0, simply update vue-template-compiler.
If you are using vue-loader@<10.0 or vueify, re-installing vue-loader/vueify should bump vue-template-compiler to the latest.


 @ ./src/routers.js 6:0-38 53:13-19
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://192.168.2.195:8013&sockPath=/sockjs-node (webpack)/hot/dev-server.js ./src/main.js

 error  in ./src/ui/voip/conference/ConferencePortalPage.vue

Module Error (from ./node_modules/vue-loader/lib/index.js):


Vue packages version mismatch:

- vue@2.6.14 (D:\work\im\gitee\vue-chat\node_modules\vue\dist\vue.runtime.common.js)
- vue-template-compiler@2.6.12 (D:\work\im\gitee\vue-chat\node_modules\vue-template-compiler\package.json)

This may cause things to work incorrectly. Make sure to use the same version for both.
If you are using vue-loader@>=10.0, simply update vue-template-compiler.
If you are using vue-loader@<10.0 or vueify, re-installing vue-loader/vueify should bump vue-template-compiler to the latest.


 @ ./src/routers.js 16:0-77 48:15-35
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://192.168.2.195:8013&sockPath=/sockjs-node (webpack)/hot/dev-server.js ./src/main.js

 error  in ./src/ui/workspace/WorkspacePage.vue

Module Error (from ./node_modules/vue-loader/lib/index.js):


Vue packages version mismatch:

- vue@2.6.14 (D:\work\im\gitee\vue-chat\node_modules\vue\dist\vue.runtime.common.js)
- vue-template-compiler@2.6.12 (D:\work\im\gitee\vue-chat\node_modules\vue-template-compiler\package.json)

This may cause things to work incorrectly. Make sure to use the same version for both.
If you are using vue-loader@>=10.0, simply update vue-template-compiler.
If you are using vue-loader@<10.0 or vueify, re-installing vue-loader/vueify should bump vue-template-compiler to the latest.


 @ ./src/routers.js 10:0-57 40:15-28 69:13-26
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://192.168.2.195:8013&sockPath=/sockjs-node (webpack)/hot/dev-server.js ./src/main.js

 error  in ./src/ui/fileRecord/FileRecordPage.vue

Module Error (from ./node_modules/vue-loader/lib/index.js):


Vue packages version mismatch:

- vue@2.6.14 (D:\work\im\gitee\vue-chat\node_modules\vue\dist\vue.runtime.common.js)
- vue-template-compiler@2.6.12 (D:\work\im\gitee\vue-chat\node_modules\vue-template-compiler\package.json)

This may cause things to work incorrectly. Make sure to use the same version for both.
If you are using vue-loader@>=10.0, simply update vue-template-compiler.
If you are using vue-loader@<10.0 or vueify, re-installing vue-loader/vueify should bump vue-template-compiler to the latest.


 @ ./src/routers.js 8:0-60 65:13-27
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://192.168.2.195:8013&sockPath=/sockjs-node (webpack)/hot/dev-server.js ./src/main.js

 error  in ./src/ui/voip/Multi.vue

Module Error (from ./node_modules/vue-loader/lib/index.js):


Vue packages version mismatch:

- vue@2.6.14 (D:\work\im\gitee\vue-chat\node_modules\vue\dist\vue.runtime.common.js)
- vue-template-compiler@2.6.12 (D:\work\im\gitee\vue-chat\node_modules\vue-template-compiler\package.json)

This may cause things to work incorrectly. Make sure to use the same version for both.
If you are using vue-loader@>=10.0, simply update vue-template-compiler.
If you are using vue-loader@<10.0 or vueify, re-installing vue-loader/vueify should bump vue-template-compiler to the latest.


 @ ./src/routers.js 7:0-36 57:13-18
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://192.168.2.195:8013&sockPath=/sockjs-node (webpack)/hot/dev-server.js ./src/main.js

 error  in ./src/ui/voip/conference/Conference.vue

Module Error (from ./node_modules/vue-loader/lib/index.js):


Vue packages version mismatch:

- vue@2.6.14 (D:\work\im\gitee\vue-chat\node_modules\vue\dist\vue.runtime.common.js)
- vue-template-compiler@2.6.12 (D:\work\im\gitee\vue-chat\node_modules\vue-template-compiler\package.json)

This may cause things to work incorrectly. Make sure to use the same version for both.
If you are using vue-loader@>=10.0, simply update vue-template-compiler.
If you are using vue-loader@<10.0 or vueify, re-installing vue-loader/vueify should bump vue-template-compiler to the latest.


 @ ./src/routers.js 11:0-57 61:13-23
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://192.168.2.195:8013&sockPath=/sockjs-node (webpack)/hot/dev-server.js ./src/main.js

 error  in ./src/ui/main/pick/PickUserView.vue

Module Error (from ./node_modules/vue-loader/lib/index.js):


Vue packages version mismatch:

- vue@2.6.14 (D:\work\im\gitee\vue-chat\node_modules\vue\dist\vue.runtime.common.js)
- vue-template-compiler@2.6.12 (D:\work\im\gitee\vue-chat\node_modules\vue-template-compiler\package.json)

This may cause things to work incorrectly. Make sure to use the same version for both.
If you are using vue-loader@>=10.0, simply update vue-template-compiler.
If you are using vue-loader@<10.0 or vueify, re-installing vue-loader/vueify should bump vue-template-compiler to the latest.


 @ ./src/ui/common/Voip.js 2:0-53
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://192.168.2.195:8013&sockPath=/sockjs-node (webpack)/hot/dev-server.js ./src/main.js

 error  in ./src/ui/main/conversation/message/forward/ForwardMessageByCreateConversationView.vue

Module Error (from ./node_modules/vue-loader/lib/index.js):


Vue packages version mismatch:

- vue@2.6.14 (D:\work\im\gitee\vue-chat\node_modules\vue\dist\vue.runtime.common.js)
- vue-template-compiler@2.6.12 (D:\work\im\gitee\vue-chat\node_modules\vue-template-compiler\package.json)

This may cause things to work incorrectly. Make sure to use the same version for both.
If you are using vue-loader@>=10.0, simply update vue-template-compiler.
If you are using vue-loader@<10.0 or vueify, re-installing vue-loader/vueify should bump vue-template-compiler to the latest.


 @ ./src/ui/common/Forward.js 4:0-129 66:28-66
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://192.168.2.195:8013&sockPath=/sockjs-node (webpack)/hot/dev-server.js ./src/main.js

 error  in ./src/ui/main/conversation/message/forward/ForwardMessageByPickConversationView.vue

Module Error (from ./node_modules/vue-loader/lib/index.js):


Vue packages version mismatch:

- vue@2.6.14 (D:\work\im\gitee\vue-chat\node_modules\vue\dist\vue.runtime.common.js)
- vue-template-compiler@2.6.12 (D:\work\im\gitee\vue-chat\node_modules\vue-template-compiler\package.json)

This may cause things to work incorrectly. Make sure to use the same version for both.
If you are using vue-loader@>=10.0, simply update vue-template-compiler.
If you are using vue-loader@<10.0 or vueify, re-installing vue-loader/vueify should bump vue-template-compiler to the latest.


 @ ./src/ui/common/Forward.js 3:0-125 31:28-64
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://192.168.2.195:8013&sockPath=/sockjs-node (webpack)/hot/dev-server.js ./src/main.js

 error  in ./src/ui/common/AlertView.vue

Module build failed (from ./node_modules/vue-loader/lib/index.js):
TypeError: Cannot read property 'parseComponent' of undefined
    at parse (D:\work\im\gitee\vue-chat\node_modules\@vue\component-compiler-utils\dist\parse.js:15:23)
    at Object.module.exports (D:\work\im\gitee\vue-chat\node_modules\vue-loader\lib\index.js:67:22)

 @ ./src/ui/common/Alert.js 1:0-40 27:23-32
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://192.168.2.195:8013&sockPath=/sockjs-node (webpack)/hot/dev-server.js ./src/main.js

 error  in ./src/App.vue

Module build failed (from ./node_modules/vue-loader/lib/index.js):
TypeError: Cannot read property 'parseComponent' of undefined
    at parse (D:\work\im\gitee\vue-chat\node_modules\@vue\component-compiler-utils\dist\parse.js:15:23)
    at Object.module.exports (D:\work\im\gitee\vue-chat\node_modules\vue-loader\lib\index.js:67:22)

 @ ./src/main.js 8:0-28 131:13-16
 @ multi (webpack)-dev-server/client?http://192.168.2.195:8013&sockPath=/sockjs-node (webpack)/hot/dev-server.js ./src/main.js

 error  in ./src/ui/main/MessagePage.vue

Module build failed (from ./node_modules/vue-loader/lib/index.js):
TypeError: Cannot read property 'parseComponent' of undefined
    at parse (D:\work\im\gitee\vue-chat\node_modules\@vue\component-compiler-utils\dist\parse.js:15:23)
    at Object.module.exports (D:\work\im\gitee\vue-chat\node_modules\vue-loader\lib\index.js:67:22)

 @ ./src/routers.js 17:0-52 77:13-24
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://192.168.2.195:8013&sockPath=/sockjs-node (webpack)/hot/dev-server.js ./src/main.js

 error  in ./src/ui/main/ConversationPage.vue

Module build failed (from ./node_modules/vue-loader/lib/index.js):
TypeError: Cannot read property 'parseComponent' of undefined
    at parse (D:\work\im\gitee\vue-chat\node_modules\@vue\component-compiler-utils\dist\parse.js:15:23)
    at Object.module.exports (D:\work\im\gitee\vue-chat\node_modules\vue-loader\lib\index.js:67:22)

 @ ./src/routers.js 3:0-58 28:15-31
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://192.168.2.195:8013&sockPath=/sockjs-node (webpack)/hot/dev-server.js ./src/main.js

 error  in ./src/ui/main/MultimediaPreviewPage.vue

Module build failed (from ./node_modules/vue-loader/lib/index.js):
TypeError: Cannot read property 'parseComponent' of undefined
    at parse (D:\work\im\gitee\vue-chat\node_modules\@vue\component-compiler-utils\dist\parse.js:15:23)
    at Object.module.exports (D:\work\im\gitee\vue-chat\node_modules\vue-loader\lib\index.js:67:22)

 @ ./src/routers.js 18:0-72 81:13-34
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://192.168.2.195:8013&sockPath=/sockjs-node (webpack)/hot/dev-server.js ./src/main.js

 error  in ./src/ui/main/MessageHistoryPage.vue

Module build failed (from ./node_modules/vue-loader/lib/index.js):
TypeError: Cannot read property 'parseComponent' of undefined
    at parse (D:\work\im\gitee\vue-chat\node_modules\@vue\component-compiler-utils\dist\parse.js:15:23)
    at Object.module.exports (D:\work\im\gitee\vue-chat\node_modules\vue-loader\lib\index.js:67:22)

 @ ./src/routers.js 13:0-62 85:13-31
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://192.168.2.195:8013&sockPath=/sockjs-node (webpack)/hot/dev-server.js ./src/main.js

 error  in ./src/ui/main/HomePage.vue

Module build failed (from ./node_modules/vue-loader/lib/index.js):
TypeError: Cannot read property 'parseComponent' of undefined
    at parse (D:\work\im\gitee\vue-chat\node_modules\@vue\component-compiler-utils\dist\parse.js:15:23)
    at Object.module.exports (D:\work\im\gitee\vue-chat\node_modules\vue-loader\lib\index.js:67:22)

 @ ./src/routers.js 1:0-42 24:13-21
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://192.168.2.195:8013&sockPath=/sockjs-node (webpack)/hot/dev-server.js ./src/main.js

 error  in ./src/ui/main/CompositeMessagePage.vue

Module build failed (from ./node_modules/vue-loader/lib/index.js):
TypeError: Cannot read property 'parseComponent' of undefined
    at parse (D:\work\im\gitee\vue-chat\node_modules\@vue\component-compiler-utils\dist\parse.js:15:23)
    at Object.module.exports (D:\work\im\gitee\vue-chat\node_modules\vue-loader\lib\index.js:67:22)

 @ ./src/routers.js 12:0-66 73:13-33
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://192.168.2.195:8013&sockPath=/sockjs-node (webpack)/hot/dev-server.js ./src/main.js

 error  in ./src/ui/main/ContactPage.vue

Module build failed (from ./node_modules/vue-loader/lib/index.js):
TypeError: Cannot read property 'parseComponent' of undefined
    at parse (D:\work\im\gitee\vue-chat\node_modules\@vue\component-compiler-utils\dist\parse.js:15:23)
    at Object.module.exports (D:\work\im\gitee\vue-chat\node_modules\vue-loader\lib\index.js:67:22)

 @ ./src/routers.js 4:0-48 32:15-26
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://192.168.2.195:8013&sockPath=/sockjs-node (webpack)/hot/dev-server.js ./src/main.js

 error  in ./src/ui/main/LoginPage.vue

Module build failed (from ./node_modules/vue-loader/lib/index.js):
TypeError: Cannot read property 'parseComponent' of undefined
    at parse (D:\work\im\gitee\vue-chat\node_modules\@vue\component-compiler-utils\dist\parse.js:15:23)
    at Object.module.exports (D:\work\im\gitee\vue-chat\node_modules\vue-loader\lib\index.js:67:22)

 @ ./src/routers.js 2:0-44 21:13-22
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://192.168.2.195:8013&sockPath=/sockjs-node (webpack)/hot/dev-server.js ./src/main.js

 error  in ./src/ui/main/fav/FavPage.vue

Module build failed (from ./node_modules/vue-loader/lib/index.js):
TypeError: Cannot read property 'parseComponent' of undefined
    at parse (D:\work\im\gitee\vue-chat\node_modules\@vue\component-compiler-utils\dist\parse.js:15:23)
    at Object.module.exports (D:\work\im\gitee\vue-chat\node_modules\vue-loader\lib\index.js:67:22)

 @ ./src/routers.js 9:0-44 36:15-22
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://192.168.2.195:8013&sockPath=/sockjs-node (webpack)/hot/dev-server.js ./src/main.js

 error  in ./src/ui/main/ConversationFloatPage.vue

**Comment by bad-pear** [comment]
我感觉今天晚上跑不起来啊，哥。我还有个问题，我将后端启动之后，使用这个能够测试吗？修改配置文件。将后台地址改为本地

**Comment by imndx** [comment]
重新更新下，这次应当好了。

如 README 所说，要专业版IM-server 才支持 web 端接入

**Comment by bad-pear** [comment]
使用开源的代码。broker项目下的broker/src/main/java/cn/wildfirechat/server/Server.java

**Comment by bad-pear** [comment]
一点也不能用吗

**Comment by bad-pear** [comment]
还是不行呀。那不玩犊子了，整半天我跟你当了半天测试，不能用
![图片](https://github.com/wildfirechat/vue-chat/assets/17894730/3a3ec6bf-3571-4414-a06b-c64e4fcf23ea)

**Comment by imndx** [comment]
Android 和 iOS 可以的，但 Web 端，需要专业版 im-server 才支持，你可以看下这儿，[申请试用](https://docs.wildfirechat.cn/trial/)

**Comment by imndx** [comment]
> 还是不行呀。那不玩犊子了，整半天我跟你当了半天测试，不能用 ![图片](https://user-images.githubusercontent.com/17894730/266591741-3a3ec6bf-3571-4414-a06b-c64e4fcf23ea.png)

端口不是 5000，是 8013

**Comment by bad-pear** [comment]
现在好了。可以启动了。

**Comment by bad-pear** [comment]
我前端都是半吊子

**Comment by bad-pear** [comment]
搞了半天。就跟你跑了两bug。。。跑完不能用
