### ISSUE TITLE
高频发消息，网页版加载不全

### ISSUE THREAD

**Issue by zenggong965** [wildfirechat/vue-chat#85]
### 背景
我们的用户反馈说有的时候网页版消息展示不全
用户有500+成员的大群，收发消息频率很高

### 模拟测试
用后端的admin接口发消息
使用bash脚本直接for循环调用接口给群里发消息
群只有5个人，用其中一个人作为发送方
用网页版登录一个接收方

### 表现
直接执行脚本发送50条消息，接收方只收到17条未读消息
接收方关闭网页版重新登录，可以收取到所有的50条消息
基本上每次都是收不全，有的时候收17，有的时候收30+

### 预期结果
网页版要能正常收取50条消息

### 其他
如果用脚本直接发100、200条消息，效果更明显

**Comment by imndx** [comment]
切换会话，在切回来，显示对吗？

**Comment by zenggong965** [comment]
> 切换会话，在切回来，显示对吗？

@imndx 切换会话不会完整收取全部消息，得关掉页面重启
近期有更新专业版web sdk吗？我们8月31日申请升级了一次，9与4日又买了一批，这两批的版本一样吗？

**Comment by zenggong965** [comment]
@imndx 过好长时间最终能收全消息，但是这个时间和手机端没法比，手机端马上就能收全
看编号，我试了100条，0到99
![image](https://github.com/wildfirechat/vue-chat/assets/11338629/f8338076-5469-43a6-83af-c6a8dcc90d0d)

**Comment by imndx** [comment]
已修复
