### ISSUE TITLE
复制记事本多行文本，黏贴后内容多出一行换行

### ISSUE THREAD

**Issue by FelicityCiao** [wildfirechat/vue-chat#87]
现象如图：

![web-复制txt文本黏贴后会换行](https://github.com/wildfirechat/vue-chat/assets/5611610/44c047ca-57e8-48b3-b7b5-e7ce54ffe127)

**Comment by imndx** [comment]
问题应当已解决，请用我们[线上 demo](https://web.wildfirechat.cn)对比下

**Comment by zenggong965** [comment]
> 问题应当已解决，请用我们[线上 demo](https://web.wildfirechat.cn)对比下

@imndx 上面那个截图就是你们的线上demo，我刚才又测了一下还是这样。从记事本复制多行内容过来粘贴发送，就会产生多余的空行

**Comment by zenggong965** [comment]
@imndx 发送出去的带空行的消息，直接右键复制再粘贴不会有空行，如果是鼠标拖动高亮复制就会连带空行一起复制
![image](https://github.com/wildfirechat/vue-chat/assets/11338629/e2a50b08-23b9-4d21-915a-7899dbb506c3)

**Comment by imndx** [comment]
这个可能是换行符`\r\n`问题
