### ISSUE TITLE
“逐条转发”聊天消息至多个会话，消息发送失败

### ISSUE THREAD

**Issue by FelicityCiao** [wildfirechat/vue-chat#94]
操作：
群聊会话中，多选混合文字、图片等文件的消息内容（约10条），选择逐条转发，勾选9-30个左右会话，发送。

现象：
大约有8-9个会话的消息全部发送成功，其余皆失败，失败的消息还会显示部分已读，如图1/3已读。

概率：不是必现，但高概率出现失败的情况。

预期：
转发消息不应该失败

**Comment by FelicityCiao** [comment]
![野火issue-转发消息发送失败](https://github.com/wildfirechat/vue-chat/assets/5611610/025ded88-3253-4f08-8122-3af4f5621e7d)

**Comment by imndx** [comment]
失败的错误码是什么？

**Comment by imndx** [comment]
可能是超频，默认客户端请求频率限制是 10 秒 100 次，具体配置可以看 im-server 的配置文件：
```
##客户端请求频率限制，默认是10秒100次。通常情况下不要修改这个值。
client.request_rate_limit 100
```

10 条消息，分发到 9-30 个会话，中间不加延时的话，会触发超频。
