### ISSUE TITLE
刷新加载网页版，会话列表中的会话数会概率性地变少

### ISSUE THREAD

**Issue by FelicityCiao** [wildfirechat/vue-chat#96]
两种操作方式：
方式一. 刷新网页再加载，或者久置不活跃后刷新重新登录账号
方式二. 同时登录客户端版与网页版

现象：
网页版会话数变少，某些会话莫名消失了。
概率较高

第二种操作方式方便对比：
客户端的列表数是全的，网页版数量少于客户端版
如图1+2客户端会话数16个：
![野火-客户端会话数01](https://github.com/wildfirechat/vue-chat/assets/5611610/8c83e59d-bc4f-4965-b8a3-5560ee05b48e)
![野火-客户端会话数02](https://github.com/wildfirechat/vue-chat/assets/5611610/c365109e-1547-4ff1-b05a-0e801c731c92)

图3+4网页版会话数13个：
![野火-web会话列表01](https://github.com/wildfirechat/vue-chat/assets/5611610/9dc3bab5-a830-4d98-b3fa-34ceaacbbf46)
![野火-web会话列表02](https://github.com/wildfirechat/vue-chat/assets/5611610/127849e6-fa01-427e-991b-d6301846918b)

**Comment by imndx** [comment]
web 端的会话列表是根据会话设置、已读状态、最近100条消息等条件生成的，当某个会话最近一条消息在整体最近 100 条消息之前，且没有任何该会话的相关设置的话，就没法生成这个会话。

**Comment by FelicityCiao** [comment]
> web 端的会话列表是根据会话设置、已读状态、最近100条消息等条件生成的，当某个会话最近一条消息在整体最近 100 条消息之前，且没有任何该会话的相关设置的话，就没法生成这个会话。

用户的角度，只在意最近会话。同一段时间的会话如果有的显示有的消失，就不太好。

**Comment by FelicityCiao** [comment]
100条数值可以修改吗？和 message.max_queue 是同一个值吗？

**Comment by imndx** [comment]
> 100条数值可以修改吗？和 message.max_queue 是同一个值吗？

是`message.web_roaming_count`

**Comment by imndx** [comment]
> > web 端的会话列表是根据会话设置、已读状态、最近100条消息等条件生成的，当某个会话最近一条消息在整体最近 100 条消息之前，且没有任何该会话的相关设置的话，就没法生成这个会话。
> 
> 用户的角度，只在意最近会话。同一段时间的会话如果有的显示有的消失，就不太好。

是的，但web 端，由于浏览器的限制，功能会比 pc 端弱，pc 端不会出现这种情况。
