### ISSUE TITLE
通过密码验证方式修改密码失败

### ISSUE THREAD

**Issue by FelicityCiao** [wildfirechat/vue-chat#98]
设置-修改密码-密码验证

现象：重置密码失败，服务器异常

对比：短信方式修改密码正常

**Comment by imndx** [comment]
用 demo 测试，未复现。

可用我们线上测试一下：https://web.wildfirechat.cn/

**Comment by FelicityCiao** [comment]
chrome: 异常提示
<img width="375" alt="截屏2023-12-06 16 57 49" src="https://github.com/wildfirechat/vue-chat/assets/5611610/f84540f9-c009-4516-a1e5-ef7b86935133">
safari:
确认修改键灰色，无法修改
<img width="342" alt="image" src="https://github.com/wildfirechat/vue-chat/assets/5611610/fc776977-8376-4d82-9210-a4670cead23a">

**Comment by imndx** [comment]
> chrome: 异常提示 <img alt="截屏2023-12-06 16 57 49" width="375" src="https://private-user-images.githubusercontent.com/5611610/288349548-f84540f9-c009-4516-a1e5-ef7b86935133.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE4Njc5MjUsIm5iZiI6MTcwMTg2NzYyNSwicGF0aCI6Ii81NjExNjEwLzI4ODM0OTU0OC1mODQ1NDBmOS1jMDA5LTQ1MTYtYTFlNS1lZjdiODY5MzUxMzMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIwNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMDZUMTMwMDI1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NjNlNjhmMWZiZWQ0Y2RmZmM5MWJiZjY3N2E1ZTMyYzFiNWI0Zjc5ZGE5YmI5ZTdmNDQ3YzM4ZDdiMmJlNGZjMCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.72MxvXYpK_wH77C8hgZtAw6KmKO9-FEtB7ZGU4NX-So"> safari: 确认修改键灰色，无法修改 <img alt="image" width="342" src="https://private-user-images.githubusercontent.com/5611610/288350956-fc776977-8376-4d82-9210-a4670cead23a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE4Njc5MjUsIm5iZiI6MTcwMTg2NzYyNSwicGF0aCI6Ii81NjExNjEwLzI4ODM1MDk1Ni1mYzc3Njk3Ny04Mzc2LTRkODItOTIxMC1hNDY3MGNlYWQyM2EucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIwNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMDZUMTMwMDI1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NDNkNGE3OTQzNWJkN2NlM2UzODMxNzUyYjdjYjU5YzQ1NGFiMjA5MmNjNTc3NWY3ODFmNjdhZmVjYTA2NmUzYiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.aVnntJHbr9J_0eqxnUq3LgYehc0-LEhFgfLH_I6JRDk">

这是用我们线上 demo 测试的？

**Comment by FelicityCiao** [comment]
是的。

**Comment by imndx** [comment]
你好，我们这边还是复现不了，请你提供下 app-server 的日志，我们分下.
